[tool.poetry]
name = "serpents"
version = "0.1.0"
description = ""
authors = ["Sasha Lopoukhine <sasha@lopoukhine.com>"]
readme = "README.md"
packages = [{ include = "graps" }]

[tool.poetry.dependencies]
python = "^3.10"
xdsl = "^0.16.0"
pyright = "^1.1.347"
pytest = "^7.4.4"
numpy = "^1.26.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
enableTypeIgnoreComments = false
typeCheckingMode = "strict"
"include" = ["serpents"]

[tool.isort]
profile = "black"

[tool.ruff]
select = ["E", "F", "W", "I", "UP", "PT"]
line-length = 90
target-version = "py310"

[tool.ruff.mccabe]
max-complexity = 10
