# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI - Pyright

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    env:
      PYRIGHT_VERSION: 1.0

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: retrieve pyright version
        run: |
          VER=$(grep -o 'pyright = "[^"]*"' pyproject.toml | sed 's/pyright = "^\(.*\)"/\1/')
          echo "PYRIGHT_VERSION=$VER" >> $GITHUB_ENV

      - name: Pyright
        uses: jakebailey/pyright-action@v2
        with:
          version: ${{ env.PYRIGHT_VERSION }}
